# prometheus.yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Prometheus теперь собирает ТОЛЬКО метрики Alloy
scrape_configs:
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]
    scrape_interval: 15s

# Правила алертинга
rule_files:
  - "alerts.yml"

# Alertmanager (опционально)
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
