services:
  postgres:
    image: postgres:18.1-alpine3.22
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - app-network
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    environment:
      # вынести в секреты
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: subs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
